name: Download Configuration
on:
  schedule:    
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Downloading Configuration File
      run: |
        echo Downloading Configuration File
        wget https://streetpass.test72.eu.org/downloadJson -O /home/runner/work/streetpass-shop/streetpass-shop/unistore/StreetPass-Shop.unistore
    - uses: stefanzweifel/git-auto-commit-action@v4
